### ISSUE TITLE
Add documentation on modification date support

### ISSUE THREAD

**Issue by dkocher** [iterate-ch/docs#10]
Provide chart with protocols wether they support retaining the modification date when uploading files.

**Comment by tatze96** [comment]
To which protocols does this apply?

**Comment by dkocher** [comment]
Protocols with support for retaining modification dates

- SFTP
- Google Drive
- Google Storage
- Microsoft OneDrive
- Microsoft Sharepoint
- Files.com
- DRACOON

Protocols with limited support retaining modification dates for new files uploaded but without the option to adjust the modification date later (only relevant for Mountain Duck)

- Backblaze B2 (using `src_last_modified_millis`)
- Box
- Dropbox
- Nextcloud (using `X-OC-Mtime`)
- ownCloud (using `X-OC-Mtime`)


Protocols with possible interoperability issues

- WebDAV. Saving the modification dates requires support from server storing metadata in custom namespace
- FTP. Requires support from server for `MFMT` or `UTIME` extensions

Support in S3 only with connection profile _S3 (Timestamps)_.
