### ISSUE TITLE
Please add connection profile for Alibaba cloud object storage service

### ISSUE THREAD

**Issue by cyl33922073** [iterate-ch/docs#118]
Can you add alibaba cloud OSS to the support list? OSS is S3 compatible: https://www.alibabacloud.com/help/en/doc-detail/64919.html

**Comment by dkocher** [comment]
Current documentation in [Alibaba Cloud Object Storage Service (OSS)](https://docs.cyberduck.io/protocols/s3/alibaba/).

**Comment by dkocher** [comment]
Documentation in https://docs.cyberduck.io/protocols/s3/alibaba/ should be amended with information about connection profiles.
