### ISSUE TITLE
8.2.0 macOS prompting for password while using SSH keys

### ISSUE THREAD

**Issue by ksystems** [iterate-ch/docs#119]
We have discovered a bug while using Cyberduck version 8.2.0.  When setup to use SSH keys for connection to SFTP server, it continues to prompt for password.

We have resolved by downgrading to version 8.0 which works perfectly as expected.

**Comment by ylangisc** [comment]
Duplicate for https://github.com/iterate-ch/cyberduck/issues/12733.
