### ISSUE TITLE
Review Connection Profiles

### ISSUE THREAD

**Issue by tatze96** [iterate-ch/docs#131]
There are two connection profiles set on the corresponding wiki page but only one connection profile for Oktawave can be found within the *Profiles* tab of the preferences. Additionally, both of the set connection profiles only can be downloaded from an external source.

**Comment by tatze96** [comment]
same for iDrive S3 and Polycloud

**Comment by tatze96** [comment]
For Eucalyptus Walrus the connection profile is missing completely.

**Comment by tatze96** [comment]
For GMX Cloud the wrong URL to the connection profile is set.

**Comment by dkocher** [comment]
In #576.
