### ISSUE TITLE
Add table contents to each page

### ISSUE THREAD

**Issue by AliveDevil** [iterate-ch/docs#149]
Should we provide a table of contents on each page of the documentation to include all anchors, that are now not part of the left side navigation?

![image](https://user-images.githubusercontent.com/734738/152133680-55fb17f2-78e0-4d7d-bfff-2c9f965b9767.png)

Directive for Sphinx: [Table of Contents](https://docutils.sourceforge.io/docs/ref/rst/directives.html#table-of-contents)

**Comment by dkocher** [comment]
Possibly on selected pages only.

**Comment by AliveDevil** [comment]
Fair enough. Possibly longer documents with many and/or multiple levels of headers?

**Comment by AliveDevil** [comment]
Checking through the docs I found:
* Cyberduck
  * Bookmaks
  * Browser
  * Opening Connections
  * FAQ
  * Info window
  * Share Files
  * File Transfers
* Mountain Duck
  * User Interface
  * Known Issues
  * Smart Synchronization
  * Preferences
* Protocols
  * Swift
  * S3
  * WebDAV
  * Backblaze
  * FTP
  * Google Cloud
  * SFTP
* Cryptomator
