### ISSUE TITLE
Enhance Windows Installer-documentation

### ISSUE THREAD

**Issue by AliveDevil** [iterate-ch/docs#153]
Sometimes the Windows Installer goes haywire and is completely confused about installed products, resulting in non-modifiable state of products.
Document steps to troubleshoot:
```cmd
reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall" /s /f "Product Name"
reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Products" /s /f "Product Name"
```

Results in something like:
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{23067521-119B-4B0A-BCDD-38835D58077B}
    DisplayName    REG_SZ    Cyberduck
```

Delete that key by `reg delete "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{23067521-119B-4B0A-BCDD-38835D58077B}" /f`

```
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Products\12576032B911A0B4CBDD8338D58570B7
    ProductName    REG_SZ    Cyberduck

HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Products\12576032B911A0B4CBDD8338D58570B7\SourceList
    PackageName    REG_SZ    Cyberduck-Installer-8.2.3.36825.msi
```

Delete that by `reg delete "HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Products\12576032B911A0B4CBDD8338D58570B7" /f`.

Restart system, installer shouldn't complain anymore.

**Comment by dkocher** [comment]
Also provide regular uninstall usage from the command line

```
Mountain Duck Installer-<version>.exe /uninstall
```
* Uninstall without displaying the user interface:
```
Mountain Duck Installer-<version>.exe /uninstall /quiet
```
