### ISSUE TITLE
Review preferences handling

### ISSUE THREAD

**Issue by ylangisc** [iterate-ch/docs#170]
Make documentation consistent regarding preferences handling on macOS, i.e. `~/Library/Preferences/ch.sudo.cyberduck.plist` vs. `~/Library/Containers/ch.sudo.cyberduck/Data/Library/Preferences/ch.sudo.cyberduck.plist` vs. `ch.sudo.cyberduck`.

**Comment by dkocher** [comment]
With 2ccd1ddb.
