### ISSUE TITLE
Add connection profile for Cloudflare R2

### ISSUE THREAD

**Issue by dkocher** [iterate-ch/docs#198]
See https://github.com/iterate-ch/cyberduck/issues/13376

**Comment by dkocher** [comment]
Add information about CloudFlare R2 in [S3](https://docs.cyberduck.io/protocols/s3/) and dedicated page https://docs.cyberduck.io/protocols/s3/cloudflare respectively.

**Comment by dkocher** [comment]
The [connection profile](https://github.com/iterate-ch/cyberduck/blob/master/profiles/Cloudflare%20R2%20Storage%20(S3).cyberduckprofile) is now available in _Preferences → Profiles.

**Comment by samducker** [comment]
is it possible to add a domain alias for sharing links of public buckets @dkocher ?

**Comment by dkocher** [comment]
> is it possible to add a domain alias for sharing links of public buckets @dkocher ?

Currently this has to be set in the bookmark (using Cyberduck) by setting a domain in the _Web URL_ [^1]. It would be nice if we add support for a default in a connection profile.

[^1]: https://docs.cyberduck.io/cyberduck/bookmarks/#http-url
