### ISSUE TITLE
Mountain Duck FAQ 

### ISSUE THREAD

**Issue by Cassie205** [iterate-ch/docs#201]
Add a FAQ page for Mountain Duck.

**Comment by Cassie205** [comment]
- ASF
- Reload
- Finder Extension
- file caching (when, where) + Disk space/ CM
- Licensing (old Licenses)
- Web URL

**Comment by dkocher** [comment]
Other issues to be covered

### Cancel synchronization

- [ ] How to cancel upload in progress
- [ ] How to cancel _Keep Offline_ process


### Synchronize files in _Ignored_ state or _Error_ state
- [ ] Retry when _Error_ badge
- [ ] When target directory does not exist on server, file must be moved to location that exists on server as well
- [ ] _Ignored_ files need to be renamed to be uploaded

### Disk space

- [ ] Temporary files lifecycle
- [ ] How does _Enable Buffer_ affect disk space usage
- [ ] How to clear up disk space
- [ ] Auto cache management 
- [ ] Disk Usage in _Online_ connect mode

### Indexer

- [ ] Disabled Indexer option will delay discovery of new files. Deleted and added files not updated in background on volume when indexing is paused
- [ ] No indexing of files and folders when in _Online_ connect mode. You cannot browse folders when no connection to the server is possible.

### Run as Windows Service

- [ ] It isn't possible to run Mountain Duck as a Service as it needs an interactive user session to mount drives. As the mounts are also limited to the user session there isn't any way to mount a drive once and share it with all other users.

###Windows Installation

- [ ] Undefined error with code 0x24c

`A volume has been accessed for which a file system driver is required that has not yet been loaded.`

**Comment by Cassie205** [comment]
please elaborate more on the technical part of

- [ ] Temporary files lifecycle

**Comment by Cassie205** [comment]
@dkocher Please add information on 'Temporary file lifecycle' and check the PR
