### ISSUE TITLE
Add versioning documentation for protocols

### ISSUE THREAD

**Issue by tatze96** [iterate-ch/docs#206]
Version: Mountain Duck 4.12/Cyberduck 8.4

A list of the file versions can be viewed within the _Version_ tab of the Info window. The files can also be reverted to a chosen version in the same section.

- [ ] _Mountain Duck_: The *Versions* option will be removed from the context menu.

Support has been added for the following protocols and should be mentioned in the protocol documentation
- [ ] B2: Possibility to revert files will be added.
- [ ] Dropbox
- [ ] Google Drive
- [ ] OneDrive
- [ ] Sharepoint
- [ ] DRACOON

Adjust the information on the following pages:

- [ ] https://docs.cyberduck.io/protocols/s3/#versions
- [ ] https://docs.cyberduck.io/protocols/b2/#file-versioning

### Cyberduck & Mountain Duck Info Panel
- [ ] #202 

### Mountain Duck
- [ ] https://docs.mountainduck.io/mountainduck/versions/

**Comment by dkocher** [comment]
The following protocols now have support to review previous versions of files in _Info → Versions_. Some protocols also display previous versions of files in _Cyberduck_ browser when enabling  _View → Show Hidden_.

| Protocol  | Revert previous version | Open/Quick Look previous version | Delete version | Displayed in browser with _View → Show Hidden_ |
| - | - | - | - | - |
| Google Drive | ❌ | ✅ | ✅ | ✅ |
| Dropbox | ❌ | ✅ | ✅ | ❌ |
| S3 | ✅ | ✅ | ✅ | ✅ |
| Google Storage | ✅ | ✅ | ✅ | ✅ |
| Microsoft OneDrive | ✅ | ✅ | ❌ | ❌ | 
| Microsoft Sharepoint | ✅ | ✅ | ❌ | ❌ | 
| DRACOON | ✅ | ❌ | ❌ | ❌ |

**Comment by tatze96** [comment]
relates to #202
