### ISSUE TITLE
Documentation for Seagate Lyve Cloud

### ISSUE THREAD

**Issue by dkocher** [iterate-ch/docs#235]
- [ ] https://docs.cyberduck.io/protocols/s3/

> https://help.lyvecloud.seagate.com/en/s3-api-endpoint.html

References 
 * https://help.lyvecloud.seagate.com/en/using-cyberduck.html
 * https://help.lyvecloud.seagate.com/en/using-mountain-duck.html

**Comment by Mojomondo** [comment]
Waiting for our new cars request for Lyve cloud buckets
