### ISSUE TITLE
Add profile for eu-east-1.s3.storadera.com

### ISSUE THREAD

**Issue by tahke** [iterate-ch/docs#248]
Refer to the [documentation](https://docs.cyberduck.io/protocols/profiles/) on connection profiles.
Protocol: S3
Vendor: Storadera
Description: Secure and affordable unlimited data storage for creating archives and backups.
Free up local storage, restore backups from anywhere and mitigate local disaster risk with Storadera. No minimum file size, no delete penalties time and no upper data limit.

**Comment by ylangisc** [comment]
@tahke Please add a connection profile with your settings according to the documentation above. Also refer to the [3rd party S3 providers](https://docs.cyberduck.io/protocols/s3/#third-party-providers) as a basis.
