### ISSUE TITLE
Is it possible to designate folders or files as "local-only"?

### ISSUE THREAD

**Issue by jvsteiner** [iterate-ch/docs#289]
Sometimes I'd like to not bother syncing files in my workspaces, for example when I have environmental or hidden folders.  For example, I have a `.obsidian` folder with config stuff in it, which I do not want to sync. How do I do that?  I am using Mountain Duck

**Comment by dkocher** [comment]
This is currently only configurable with a [hidden configuration option](https://docs.mountainduck.io/mountainduck/preferences/#hidden-configuration-options) defaulting to:

```
fs.filenames.temporary.regexp=\\.nfs\\..* \\.VolumeIcon.icns \\.DS_Store .*~$ .*~\\..* \\._~\\$.* \\.~(?!lock).*[^#] .*\\.tmp ~.*\\.tmp .*~.*\\.TMP .*\\.swap .*\\.swp Word\\sWork\\sFile.*\\.tmp \\._Word\\sWork\\sFile.*\\.tmp (.*)\\.sb-[\\w]{8}-[\\w]{6} \\._.*\\.(doc|docx)\\.sb-.* \\.TemporaryItems \\.dat\\.nosync.* DBTmp.* .*\\.lck [0-9A-Z]+\\.tmp .*\\.idlk Desktop\\.ini desktop\\.ini Thumbs\\.db \\(A\\ Document\\ Being\\ Saved\\ By\\ .*\\) ai[\\d]{12}.* AI\\ Temp.* .*\\.crdownload .*\\.part .*\\.onetmp
```
