### ISSUE TITLE
Documentation on protocols reporting quota to display as available disk space

### ISSUE THREAD

**Issue by dkocher** [iterate-ch/docs#353]
Add table showing which protocols report available quota and thus occupied and available disk space is displayed on the mounted volume.

**Comment by tatze96** [comment]
- OneDrive can only display the correct quota if a path other than the top level folder is mounted.
- S3 and B2 can't display quota

**Comment by dkocher** [comment]
The following protocols can report quota
* WebDAV
* Google Drive
* Dropbox
* Local Disk
* SFTP
* SMB
* OpenStack Swift
