### ISSUE TITLE
Mountain Duck and Cyberduck issues with Backblaze B2

### ISSUE THREAD

**Issue by ikeleher** [iterate-ch/docs#382]
We are having an issue where only 2 folders are showing when connecting to Backblaze B2 using Mountain Duck and also the same with Cyberduck.

During testing we have used the master key as well as all application keys were have generated.

Can I please have assistance troubleshooting this issue?

**Comment by ikeleher** [comment]
Further to my previous post, I have tested connections with ExpanDrive and all the folders are appearing.

**Comment by dkocher** [comment]
Previously discussed in [^1] with open issue [^2]. 

[^1]: iterate-ch/cyberduck#14759
[^2]: iterate-ch/cyberduck#14768

**Comment by ikeleher** [comment]
Hi David,

Can you advise how to show hidden folders in Mountain Duck?
