### ISSUE TITLE
symlink command backwards

### ISSUE THREAD

**Issue by tcurtin** [iterate-ch/docs#401]
- [ ] https://docs.cyberduck.io/cyberduck/bookmarks/#sharing-bookmarks-between-different-computers

When running symlink to connect cloud backup to application support directory, the command in Step 4 for MacOS should be
```
ln -s <CloudDirectory> <AppSupportDirectory/foldername>
```
(`ln -s` takes source then target as arguments, not the other way around)

**Comment by dkocher** [comment]
> An easy rule to remember is that the argument order for ln is the same as for cp(1): The first argument needs to exist, the second one is created.
