### ISSUE TITLE
Default paths set in protocols

### ISSUE THREAD

**Issue by dkocher** [iterate-ch/docs#45]
Some protocols have a default path set other than `/`. This should be documented and instructions given how to change the bookmark configuration. In Mountain Duck the default path is the working directory mounted with no option to browse parent folders.

- OneDrive defaults to `/My Files`
- Google defaults to `My Drive`

**Comment by tatze96** [comment]
For both OneDrive and Google Drive, the default path resolves to `/` showing the folders `My Files` and `Shared with me` for One Drive and `My Drive`, `Shared Drives`, and `Shared with me` for Google Drive.
