### ISSUE TITLE
Improve cli documentation for folder uploads

### ISSUE THREAD

**Issue by AliveDevil** [iterate-ch/docs#47]
This integrates `folder` to `name` (e.g. folder contents)
```
duck --upload protocol:/<name> folder/
```

This uploads `folder` to `<name>/` (uploads folder itself)
```
duck --upload protocol:/<name>/ folder/
```

**Comment by dkocher** [comment]
There is also [Glob pattern support for selecting files to transfer](https://docs.cyberduck.io/CLI/#glob-pattern-support-for-selecting-files-to-transfer)
