### ISSUE TITLE
Missing entries in S3 content overview

### ISSUE THREAD

**Issue by ylangisc** [iterate-ch/docs#561]
In [S3 overview](https://github.com/iterate-ch/docs/blob/main/protocols/s3/index.md) at least the entries
`AWS IAM Identity Center` and `Connecting Using AssumeRole from AWS Security Token Service (STS)` are missing in the content list at the top of the page.

**Comment by AliveDevil** [comment]
Level 4 heading aren't displayed.
Have to be promoted to level 3.
