### ISSUE TITLE
Restructure S3 Providers

### ISSUE THREAD

**Issue by Cassie205** [iterate-ch/docs#572]
- [ ] Reduce TOC 
- [ ] Combine Third-party Providers with less or no content to one side
- [ ] IBM (Link only)

**Comment by Cassie205** [comment]
Scality RS2
- [ ] Add information for Dunkel Cloud Storage
- [ ] Check information for Seaweb and NetApp

**Comment by tatze96** [comment]
**Seagate**
- [ ] Link to available endpoints is missing an "s" in between `endpoint` and `.html`.
- [ ] Add missing endpoints

**S3 Index page**
- [ ] set preferences in italics in [Bucket Access Logging](https://docs.cyberduck.io/protocols/s3/#bucket-access-logging) and [Public URLs](https://docs.cyberduck.io/protocols/s3/#public-urls)
- [ ] Move Restore from Glacier text into custom "Cyberduck Only" admonition
