### ISSUE TITLE
Add Connection Profile for pCloud

### ISSUE THREAD

**Issue by tatze96** [iterate-ch/docs#71]
### Data region: USA (Texas)
**Protocol**: WebDAV
**Default Hostname**: https://webdav.pcloud.com
**Default Port**: 443
### Data region: Europe (Luxemburg)
**Protocol**: WebDAV
**Default Hostname**: https://ewebdav.pcloud.com
**Default Port**: 443

**Comment by dkocher** [comment]
Profiles will be available with iterate-ch/cyberduck#12926
