### ISSUE TITLE
ZIP/TAR Archives - Verify information 

### ISSUE THREAD

**Issue by Cassie205** [iterate-ch/docs#82]
"Create Archive" option within the Mountain Duck doc?
[https://docs.cyberduck.io/Mountain_Duck/Interface/?highlight=archives#create-zip-archive-of-files-on-ftp-server-or-cloud-storage](https://docs.cyberduck.io/Mountain_Duck/Interface/?highlight=archives#create-zip-archive-of-files-on-ftp-server-or-cloud-storage)

Invalid Link within Cyberduck doc?
[https://docs.cyberduck.io/Cyberduck/#browser](https://docs.cyberduck.io/Cyberduck/#browser)

**Comment by dkocher** [comment]
This usage scenario is about the option to compress and uncompress files on the mounted volume with any archive utility. This is not related to [Create and Expand ZIP/TAR Archives](https://docs.cyberduck.io/Protocols/SFTP/?highlight=compress#create-and-expand-zip-tar-archives) in Cyberduck.
